### ISSUE TITLE
Package or namespace load failed 

### ISSUE THREAD

**Issue by Jian8** [thomasp85/MSGFplus#14]
Hello, 
I've tried to install MSGFplus both via Bioc and Github, without success. I encounter this issue:

`
Installing package into ‘/home/gian_ma/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘MSGFplus’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning in fun(libname, pkgname) : NAs introduced by coercion
Error: package or namespace load failed for ‘MSGFplus’:
 .onLoad failed in loadNamespace() for 'MSGFplus', details:
  call: if (as.numeric(sub(".*\"\\d\\.(\\d).*", "\\1", javaVersion[1])) < 
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/gian_ma/R/x86_64-pc-linux-gnu-library/3.5/MSGFplus’
Warning in install.packages :
  installation of package ‘./MSGFplus-master/’ had non-zero exit status
`

My java version is:
`$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
`
Ubuntu LTS 18.04

I've seen that someone experienced the same issue before, and it was supposed to be fixed.
I hope this is not trivial, and thank you for your help

**Comment by lgatto** [comment]
There's currently a pull request (#13) for this. @thomasp85 - could you check/merge it if you are happy.

**Comment by grimbough** [comment]
In the meantime you should be able to install a temporary version via:
```{r}
devtools::install_github('grimbough/MSGFplus')
```

**Comment by Jian8** [comment]
Thank you to both of you, worked out perfectly!

**Comment by MJades** [comment]
hello,
I encounter this issue in MacOS, how to do with this?
> library("MSGFplus")
Error: package or namespace load failed for ‘MSGFplus’:
 .onLoad failed in loadNamespace() for 'MSGFplus', details:
  call: if (as.numeric(sub(".*\"\\d\\.(\\d).*", "\\1", javaVersion[1])) < 
  error: missing value where TRUE/FALSE needed
In addition: Warning message:
In fun(libname, pkgname) : NAs introduced by coercion
