### ISSUE TITLE
Can't install MSGFplus

### ISSUE THREAD

**Issue by adder** [thomasp85/MSGFplus#9]
Hi,

I get an error when I try to install MSGFplus on my linux machine. MS-GF+ standalone seems to work just fine.

My java version is:
```
    java -version
    openjdk version "1.8.0_25"
    OpenJDK Runtime Environment (build 1.8.0_25-b18)
    OpenJDK 64-Bit Server VM (build 25.25-b02, mixed mode)
```
The error is:
```
* installing *source* package ‘MSGFplus’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'MSGFplus', details:
  call: if (as.numeric(sub(".*\"\\d\\.(\\d).*", "\\1", javaVersion)) < 
  error: argument is of length zero
Error: loading failed
Execution halted
    ERROR: loading failed
```

Greetz

**Comment by thomasp85** [comment]
Thanks for the bug report. It seems I was stupidly looking for a 'java version’ string in the -version output, which is obviously incompatible with openjdk. I’ll push a fix to stable and devel soon…

sorry for the inconvenience…

**Comment by thomasp85** [comment]
Fixes should be done - it might take some time to propagate to Bioconductor…

**Comment by adder** [comment]
Hi, 
Thanks for the effort!
According the NEWS file, the new msgfplus version should be 1.0.3, which is also the version in bioconductor now and the version I downloading upon installing the library in R. But I still have the exact same error. 

Greetz

**Comment by thomasp85** [comment]
The devel and release versions are not on par. Wait until the release gets bumped to 1.0.4 (probably within the next 24 h)

best

Thomas
